name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-coverage
          path: coverage/coverage-final.json
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python3 -m pytest --junitxml=junit/test-results.xml --cov=src --cov-report=xml test/unit
      - uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          path: coverage.xml

  upload-to-codecov:
    needs: [frontend-tests, backend-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
